python %~dp0\daily_index_min5.py
python %~dp0\daily_index_min15.py
python %~dp0\daily_index_min30.py
python %~dp0\daily_index_min60.py
python %~dp0\daily_index_day.py
python %~dp0\daily_once_min5.py
python %~dp0\daily_kline_min15.py
python %~dp0\daily_kline_min30.py
python %~dp0\daily_kline_min60.py
python %~dp0\daily_kline_day.py
python %~dp0\calc_xdxr.py